### ISSUE TITLE
 ECG lead error!!! ensure the leads are properly connected

### ISSUE THREAD

**Issue by davidm-public** [Protocentral/ADS1292rShield_Breakout#11]
Hi, uploaded the `text_only' arduino file, got the following:

```
Initiliziation is done
ECG lead error!!! ensure the leads are properly connected
ECG lead error!!! ensure the leads are properly connected
ECG lead error!!! ensure the leads are properly connected
etc.
```

thing is that I've placed thousands of ecg electrodes in my time, and I can honestly say that these leads are indeed connected !

**Comment by davidmoshal** [comment]
Found the problem, defective ECG electrodes.
I can confirm that the device produces perfect ECG and Respiration traces, very impressive actually.
Please close this issue (I don't have permission to do that).

**Comment by yasaswinir** [comment]
Hello David sir! Glad you could figure out the issue! Thank you so much for your acknowledgment! Please do let us know if we could be of any further service to you!

**Comment by davidm-public** [comment]
Hi there, looks like your website is down.
I'd like to order a few more of those boards.

David
