### ISSUE TITLE
Process crashes when running.  I followed instructions on Both a Mac and 64 bit windows 

### ISSUE THREAD

**Issue by JohnPatchogue** [Protocentral/ADS1292rShield_Breakout#2]
I loaded the  libraries as instructed.  Is there a version problem?  Are the libraries for process 3?  The instructions state to explicitly use process 2.2.1 which I am using.  Still the file cannot be found.  Any insight would be appreciated.
![screen shot 2017-03-12 at 5 32 08 pm](https://cloud.githubusercontent.com/assets/26369053/23837721/e48e888e-0749-11e7-928e-840c6aa7560e.png)

**Comment by VenkateshBhat** [comment]
Dear John,

Could you please try with the latest version of Processing?

**Comment by JohnPatchogue** [comment]
Thank you It works well now.
