### ISSUE TITLE
Using Raspberry Pi 3

### ISSUE THREAD

**Issue by meerasubramanian** [Protocentral/ADS1292rShield_Breakout#5]
I would like to connect the AFE _directly_ to Raspberry Pi without an Arduino.
I planned on using only the MISO, MOSI, CS(0), SCL pins from both AFE and RasPi.
Please guide me on the changes i need to make in the processing code so as to take input from the GPIO pins and plot it in Processing.

**Comment by shreythakker** [comment]
Did you figure it out or find some library that helps with interfacing the pi with the breakout board?

**Comment by shanmukhnama** [comment]
Is there some way of doing so by using the spidev library?
